DELETE FROM KPI_STG_ITEMS
WHERE rowid not in
(SELECT MIN(rowid)
FROM KPI_STG_ITEMS
GROUP BY item_id) ;

DELETE FROM KPI_STG_CLASSES
where rowid not in (SELECT MIN(ROWID) FROM KPI_STG_CLASSES GROUP BY class_id);

DELETE FROM KPI_STG_ITEM_MERCHANDISE_DEPAR
where rowid not in (SELECT MIN(ROWID) FROM KPI_STG_ITEM_MERCHANDISE_DEPAR GROUP BY ITEM_MERCHANDISE_DEPARTMENT_ID);

DELETE FROM KPI_STG_TRANSACTIONS_LINES
where rowid NOT IN (SELECT MIN(ROWID) FROM KPI_STG_TRANSACTIONS_LINES GROUP BY TRANSACTION_ID,TRANSACTION_LINE_ID);

DELETE FROM KPI_STG_CHANNEL
WHERE rowid not in
(SELECT MIN(rowid)
FROM KPI_STG_CHANNEL
GROUP BY LIST_ID) ;

DELETE FROM KPI_STG_DEPARTMENTS
WHERE rowid not in
(SELECT MIN(rowid)
FROM KPI_STG_DEPARTMENTS
GROUP BY DEPARTMENT_ID) ;

DELETE FROM KPI_STG_ITEM_MERCHANDISE_CLASS
where rowid not in (SELECT MIN(ROWID) FROM KPI_STG_ITEM_MERCHANDISE_CLASS GROUP BY ITEM_MERCHANDISE_CLASS_ID);

DELETE FROM KPI_STG_ITEM_MERCHANDISE_COLLE
where rowid not in (SELECT MIN(ROWID) FROM KPI_STG_ITEM_MERCHANDISE_COLLE GROUP BY ITEM_MERCHANDISE_COLLECTION_ID);

DELETE FROM KPI_STG_ITEM_MERCHANDISE_SUBCL
where rowid not in (SELECT MIN(ROWID) FROM KPI_STG_ITEM_MERCHANDISE_SUBCL GROUP BY ITEM_MERCHANDISE_SUBCLASS_ID);


DELETE FROM KPI_STG_LOCATIONS
where rowid not in (SELECT MIN(ROWID) FROM KPI_STG_LOCATIONS GROUP BY LOCATION_ID);

DELETE FROM KPI_STG_TRANSACTIONS
where rowid not in (SELECT MIN(ROWID) FROM KPI_STG_TRANSACTIONS GROUP BY TRANSACTION_ID,CHANNEL_ID);

ROLLBACK;

SELECT COUNT(*) FROM KPI_STG_TRANSACTIONS;


SHOW USER

DELETE FROM KPI_STG_TRANSACTIONS
where rowid not in (SELECT MIN(ROWID) FROM KPI_STG_TRANSACTIONS GROUP BY TRANSACTION_ID);

ROLLBACK; 

SELECT COUNT(*) FROM KPI_STG_TRANSACTIONS;