-----1111111

create TABLE KPI_ITEM_DIM_FLAT (SKU varchar2(100),ITEM_TYPE VARCHAR(100),BRAND varchar2(100),MERCHANDISE_DEPARTMENT VARCHAR2(120),
MERCHANDISE_DEPT_NAME varchar2(100),MERCHANDISE_COLLECTION varchar2(100),ERCHANDISE_COLLECTION_NAME varchar2(100),
MERCHANDISE_CLASS varchar2(100),MERCHANDISE_CLASS_NAME VARCHAR2(100),MERCHANDISE_SUBCLASS varchar2(100),
MERCHANDISE_SUBCLASS_NAME varchar2(100),KPI_ITEM_SKEY NUMBER);

---2---------------
insert into KPI_ITEM_DIM_FLAT (SKU varchar2(100),ITEM_TYPE VARCHAR(100),BRAND varchar2(100),MERCHANDISE_DEPARTMENT VARCHAR2(120),
MERCHANDISE_DEPT_NAME varchar2(100),MERCHANDISE_COLLECTION varchar2(100),ERCHANDISE_COLLECTION_NAME varchar2(100),
MERCHANDISE_CLASS varchar2(100),MERCHANDISE_CLASS_NAME VARCHAR2(100),MERCHANDISE_SUBCLASS varchar2(100),
MERCHANDISE_SUBCLASS_NAME varchar2(100),KPI_ITEM_SKEY NUMBER)
select ITEMS.NAME,ITEMS.TYPE_NAME,ITEMS.BRAND_NAME,ITEM_MERCHANDISE_DEPARTMENT.DESCRIPTION,ITEM_MERCHANDISE_DEPARTMENT.ITEM_MERCHANDISE_DEPARTMENT_NA,
ITEM_MERCHANDISE_COLLECTION.DESCRIPTION,ITEM_MERCHANDISE_COLLECTION.ITEM_MERCHANDISE_COLLECTION_NA,
ITEM_MERCHANDISE_CLASS.DESCRIPTION,ITEM_MERCHANDISE_CLASS.ITEM_MERCHANDISE_CLASS_NAME,
ITEM_MERCHANDISE_SUBCLASS.DESCRIPTION,ITEM_MERCHANDISE_SUBCLASS.ITEM_MERCHANDISE_SUBCLASS_NAME,ITEMS.KPI_DW_SKEY
from ITEMS,ITEM_MERCHANDISE_DEPARTMENT,ITEM_MERCHANDISE_COLLECTION,ITEM_MERCHANDISE_CLASS,
ITEM_MERCHANDISE_SUBCLASS);



commit;

